version: '3'

services:
  next-app:
    container_name: next-app
    build:
      context: ./next-app
      dockerfile: dev.Dockerfile
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
    volumes:
      - ./next-app:/app
      - /app/node_modules
    restart: always
    ports:
      - 3000:3000
    extra_hosts:
      - host.docker.internal:host-gateway
